### ISSUE TITLE
Radix tree engine

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#100]
Add `rtree` engine based on adaptive radix tree example from pmemobj

**Comment by lh2debug** [comment]
Is it the implement of "WORT: Write Optimal Radix Tree for Persistent Memory Storage Systems" ? Looking forward to the completion of this work !

**Comment by RobDickinson** [comment]
My first attempt was going to be with the radix tree currently used as a PMDK example: https://github.com/pmem/pmdk/tree/master/src/examples/libpmemobj/libart

This is an adaptive radix tree (ART) implementation, but it doesn't have all the optimizations that WORT covers...but this is a very interesting idea.  We're starting with the ART because this is an easy way to claim radix tree support, and so we can get some baseline results to compare against our other engines.  Doing a WORT implementation is a very interesting idea for future work.

**Comment by RobDickinson** [comment]
Closing as this was an interesting experiment, but we don't plan to expose the libart example officially as an engine at this time.  Instead we're putting efforts toward the new hashmap engine (#112).
