### ISSUE TITLE
New start/stop API

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#105]
The revised API `pmemkv` should elegantly support all these use-cases:
* Opening a fixed-size local pool file, creating if necessary
* Creating a fixed-size local pool file (fail if file exists)
* Opening a local pool file (fail if file does not exist)
* Opening a DAX device (previously initialized with `pmempool create`)
* Opening a fixed-size poolset (previously initialized with `pmempool create`)
* Opening a growable poolset (see https://github.com/pmem/issues/issues/382)
* Opening a local directory (for volatile engines, see #88)
* Opening more than one file/poolset at once (for future engines)

The revised API should address these gaps:
* Protect against opening a pool with an incorrect engine (previously #131)
* Provide more detailed error descriptions (previously #137)

Finish with a blog post describing the new API and the supported configurations!

Perhaps use a larger default value (1GB) for pool size when none is provided?

**Comment by RobDickinson** [comment]
As a refresher, the current API is close to libpmemobj but does not match exactly:

```
static KVEngine* Open(const string& engine, const string& path, size_t size);

KVEngine* kv = KVEngine::Open("kvtree3", "/dev/shm/pmemkv", 1073741824);  // 1 GB pool
```

When this ticket was created, it was thought that we would break `Open` into `Open` and `Create`, where the `Open` and `Create` method signatures would exactly match their libpmemobj counterparts.  This is still a strong argument if we're only using libpmemobj for developing engines that are based on a single persistent root.  But this clearly isn't flexible enough for engines requiring more than one persistent device, or more complex configuration parameters.  (both cases are true for the caching engine)

@vinser52 and I discussed an alternative idea where by convention the `path` provided to `Open` is always expected to be a directory, under which any necessary files would be created.  This is arguably simpler than what we have now, but not flexible enough for everything we might imagine in the future.

So I'm proposing that we replace `Open` with a new `Init` method, that takes parameters for the name of the engine and a single string (preferably in JSON format) that has the entire engine configuration.  The name `Init` reflects that this operation does not exactly match either `Open` or `Create` methods as implemented by libpmemobj.

```
static KVEngine* Init(const string& engine, const string& config);

// same params as prior example, just encoded in JSON
KVEngine* kv = KVEngine::Init("kvtree3", "{\"file\":\"/dev/shm/pmemkv\",\"size\":1073741824}");

// cleanly specify directory for memkind-based engines
KVEngine* kv = KVEngine::Init("vmap", "{\"dir\":\"/dev/shm\"}");

// using more than one device becomes possible
KVEngine* kv = KVEngine::Init("logtree", "{\"data\":\"/mnt/pmem1\",\"logs\":\"/mnt/pmem2\"}");

// configuration can be propagated to sub-engines
KVEngine* kv = KVEngine::Init("caching", "{\"main_engine\":\"kvtree3\",\"main_engine_config\":{\"file\":\"/dev/shm/pmemkv\",\"size\":1073741824},\"ttl_engine\":\"vmap\",\"ttl_engine_config\":{\"dir\":\"/dev/shm\"}}");
```

Our documentation (in `ENGINES.md`) would need to describe all of the supported configuration parameters for each engine since these could vary quite a bit between different engines.

FWIW this is much cleaner for the caching engine proposal, which currently looks for a JSON file name passed as an environment variable, since there is no other way at present to propagate custom configuration params to an engine.

Anyway, feedback & suggestions are welcome!
RobD

**Comment by lukaszstolarczuk** [comment]
as we discussed on the meeting it would be good idea to prepare overloaded version of this method to have also an option for:
1. load config from a file
2. load config from an object

This lead me to a thought - maybe params should be given as a struct? This is less convenient/flexible, but perhaps less error prone...?

**Comment by RobDickinson** [comment]
> load config from a file

Yes, agreed!

> This lead me to a thought - maybe params should be given as a struct? This is less convenient/flexible, but perhaps less error prone...?

I'd rather not support structs, because those structs would have to be defined in advance.  A big part of the appeal of JSON is that the engine (rather than the pmemkv core) can define what structure the configuration data should take.  Success here is being able to define new engines in the future without having to change the pmemkv core.

**Comment by RobDickinson** [comment]
After trying out these changes locally, I think it's better if we replace `Open/Close` with `Start/Stop`.

The reason why we were recommending the name `Init` was to avoid comparing this directly with `Open` (which has different semantics).  But it turns out PMDK already uses `init/initialize` in code and docs, so we don't want to invite that comparison either.

So the new convention for pmemkv will be that engines are started and then stopped.  The start operation can involve multiple `Create` and/or `Open` calls to pmemobj (if multiple pools are used) and may also initialize data structures under the hood.  The stop operation similarly can involved multiple `Close` calls if multiple pools are used.

Words matter! :smiley:

**Comment by RobDickinson** [comment]
Implemented in all bindings!
