### ISSUE TITLE
Create a kv store with multiple files that are not fully pre-allocated bit instead get extended in chunks

### ISSUE THREAD

**Issue by chloe-alverti** [pmem/pmemkv#1051]
# QUESTION: 
Hello to all!

I am new to all this and I am trying to use pmemkv and pmemkv_bench --benchmark=fillseq 
to create a db with multiple files that are not entirely pre-allocated 
(instead they get extended gradually with multiple fallocate syscalls in chucks).
Is that possible? 

Thank you very much in advance for all your help!
Best regards,
Chloe

**Comment by igchor** [comment]
Hello!

To achieve this you can use poolsets. Here is a description of this feature: https://pmem.io/pmdk/manpages/linux/master/poolset/poolset.5 
Particulary, the "DIRECTORIES" section seems like what you are looking for.

Here you can find a pmemkv example which uses poolsets: https://github.com/pmem/pmemkv/blob/master/examples/pmemkv_open_cpp/pmemkv_open.cpp

For pmemkv-bench it should be enough to pass path to a poolset via `--db` parameter.

Will this work for you?

**Comment by chloe-alverti** [comment]
Thank you very much! Yes this is perfect!

**Comment by igchor** [comment]
Great! Feel free to open a new issue or reopen this one if you have more questions.
