### ISSUE TITLE
having problem while building the source code

### ISSUE THREAD

**Issue by yux20000304** [pmem/pmemkv#1052]
# QUESTION: missing config.h while building

## Details

i have followed all the instructions in readme.md, but i still met with the problem:  

  > Generating docs for compound pmem::kv::db...
    In file included from /usr/local/include/pmem_allocator.h:14,
                     from /home/yyx/pmemkv/src/engines/memkind_allocator_wrapper.h:7,
                     from /home/yyx/pmemkv/src/engines/vcmap.h:8,
                     from /home/yyx/pmemkv/src/engines/vcmap.cc:4:
    /usr/local/include/memkind.h:12:10: fatal error: config.h: no such file or directory
       12 | #include <config.h>
          |          ^~~~~~~~~~
  > compilation terminated.

i just wanna know why would this happen and how to solve it?

**Comment by lukaszstolarczuk** [comment]
Hi @yux20000304,

can you please provide more details, at least:
- what version of pmemkv you're installing (at best, please paste here the output of `git describe` command)?
- what exact commands did you execute before this happened?
- what OS you're running this on?

and anything else that could be helpful to reproduce this.

**Comment by yux20000304** [comment]
here are as follows:
- output of git describe command :  1.5.0-37-g0337b2d
- i follow the readme.md about installing on ubuntu, after installing PMDK, PMDK C++ bindings, memkind and other dependencies, then i run:
```
git clone https://github.com/pmem/pmemkv
cd pmemkv
mkdir ./build
cd ./build
cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug    # run CMake, prepare Debug version
make -j4
```
the error happens while i do make -j4 command
- i run all the commands on ubuntu20.04

**Comment by igchor** [comment]
@yux20000304 what version of memkind are you using? Is it some release version or you've build it from sources?

**Comment by yux20000304** [comment]
```
yyx@yyx-XPS-13-9365:~/memkind$ git describe 
v1.12.0-23-g467d7777
```

**Comment by yux20000304** [comment]
i just git clone the memkind repo from github and follow build it from sources

**Comment by igchor** [comment]
I belive It's a problem with memkind - there should be a fix for this soon. In the meantime, could you try using memkind v1.12.0?

**Comment by yux20000304** [comment]
ok, i'll try it later, thanks a lot!

**Comment by yux20000304** [comment]
you're right, that problem is solved!

**Comment by igchor** [comment]
Great! By the way, there is already a fix in memkind: https://github.com/memkind/memkind/commit/834b8d93ae87dbe1dda7f616bfb56200de4ab370 So now, master branch should also work.

I'll close the issue, but if you have any more problems feel free to reopen/create a new one.
