### ISSUE TITLE
Are there any Golang binding coming?

### ISSUE THREAD

**Issue by lonnietc** [pmem/pmemkv#1064]
I am experimenting with pmemkv and would like to be able to bind to a Golang application.

Are there any Golang bindings coming in the near future?

**Comment by lukaszstolarczuk** [comment]
Hi,

we've had some talks about it, but unfortunately never had time to do this. The only thing I know related to golang bindings for pmemkv is the old issue: https://github.com/pmem/pmemkv/issues/190
As you can see there, there was some attempt to introduce these bindings, outside of our organization. I believe we haven't tested them and I'm not sure what is the status.
