### ISSUE TITLE
Windows VS 2022 Build solutions?

### ISSUE THREAD

**Issue by lonnietc** [pmem/pmemkv#1073]
Hello,

I have just started working with PMDK which I have compiled on my VS 2022 (Windows) system and am looking to try and build the "pmemkv" libraries and examples.

Are there any VS 2022 solution files that I can experiment with?

**Comment by lukaszstolarczuk** [comment]
Hi,

unfortunately, we didn't introduce Windows support into pmemkv.

As of right now, Windows is supported in [PMDK](https://github.com/pmem/pmdk) and in [C++ bindings of libpmemobj](https://github.com/pmem/libpmemobj-cpp).

**Comment by lonnietc** [comment]
@lukaszstolarczuk Thanks for the reply on this.

Are there any plans to have Windows support in the near future?

**Comment by lukaszstolarczuk** [comment]
As I just answered in your other issue - we work with very limited resources. This, also, is not on top of our priorities, I'm afraid.

**Comment by lonnietc** [comment]
Thanks again and I will see what I can do on this end.

**Comment by igchor** [comment]
@lonnietc AFAIK we don't use any OS-specific functions in the code. It should be fairly simple to make it compile on Windows. You might need to fix some compiler errors and change CMakeLists.txt a bit (you can take a look here to see what changes are needed for Windows to work: https://github.com/pmem/libpmemobj-cpp/blob/master/CMakeLists.txt). As @lukaszstolarczuk said, we don't have resources to maintain and test the Windows version. However, feel free to send us any code patches you might come up with if you try to make it work.
