### ISSUE TITLE
Feature flags

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#116]
APIs to ask an engine at runtime about its capabilities:
* IsDefault?  (whether an engine is the current system default)
* IsDurable?   (some engines will be purely volatile, others will durably store data)
* IsThreadSafe?  (some engines are optimized for single-threaded apps)
* IsCountable? (not all engines are required to support Count operation)
* IsIterable?  (not all engines are required to support each/like methods)
* IsModifiable?  (whether put & remove are allowed against existing keys)
* IsSorted? (whether iterators return keys in sorted order?)

**Comment by szyrom** [comment]
agreed not to extend API in this way
