### ISSUE TITLE
Configure continuous integration server

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#120]
items to do:
- [x] add files needed for travis to make run all PRs, based on pmem/libpmemobj-cpp/pull/4 (PR with travis on cpp repo) -- this should be tested on fork, after tests are done it should be enabled (by a one-click) by Marcin
- [x] add valgrind to build (#135)
- [x] possibly add coverage checks, may be based on ... (coverage PR in cpp repo)
- [x] possibly add coverity scans; may be based on pmem/libpmemobj-cpp/pull/6

**Comment by lukaszstolarczuk** [comment]
items to do:
- [ ] add files needed for travis to make run all PRs, based on [https://github.com/pmem/libpmemobj-cpp/pull/4](PR with travis on cpp repo) -- this should be tested on fork, after tests are done it should be enabled (by a one-click) by Marcin
- [ ] possibly add coverity, may be based on [https://github.com/pmem/libpmemobj-cpp/pull/6/files](coverity PR in cpp repo)
- [ ] possibly add quickbuild building system for pmemkv, IF we need Klocwork & Protex for SDL process
