### ISSUE TITLE
btree tests fail under valgrind

### ISSUE THREAD

**Issue by lplewa** [pmem/pmemkv#124]
I run pmemkv tests under memcheck and pmemcheck (https://github.com/pmem/valgrind/), and it found few bugs in the btree engine. 

### steps to reproduce:
**build** pmemkv in debug version (in relase version logs from valgrind will not contain full stacktraces)
**run(pmemcheck):** 
`PMEM_IS_PMEM_FORCE=1 valgrind --tool=pmemcheck ./pmemkv_test --gtest_filter="BTreeTest.*"`
**run(memcheck):**
`PMEM_IS_PMEM_FORCE=1 valgrind --leak-check=full --show-leak-kinds=all --tool=memcheck ./pmemkv_test --gtest_filter="BTreeTest.*"`

### an example output: 
`==4100== [1]    at 0x4CE60A8: persistent::internal::b_tree_base<pstring<20ul>, pstring<200ul>, 64ul>::garbage_collection() (persistent_b_tree.h:1152)
==4100==    by 0x4CE460E: pmemkv::btree::BTreeEngine::Recover() (btree.cc:177)
==4100==    by 0x4CE3863: pmemkv::btree::BTreeEngine::BTreeEngine(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) (btree.cc:60)
==4100==    by 0x43651F: BTreeEngineBaseTest<536870912ul>::Open() (btree_test.cc:63)
==4100==    by 0x43610B: BTreeEngineBaseTest<536870912ul>::Reopen() (btree_test.cc:58)
==4100==    by 0x4316D0: BTreeEngineTest_UsePreallocAfterMultipleLeafRecoveryTest_Test::TestBody() (btree_test.cc:708)
==4100==    by 0x493219: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/user/nvml/pmemkv/pmemkv/bin/pmemkv_test)
==4100==    by 0x48DE70: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/user/nvml/pmemkv/pmemkv/bin/pmemkv_test)
==4100==    by 0x4731E9: testing::Test::Run() (in /home/user/nvml/pmemkv/pmemkv/bin/pmemkv_test)
==4100==    by 0x473A91: testing::TestInfo::Run() (in /home/user/nvml/pmemkv/pmemkv/bin/pmemkv_test)
==4100==    by 0x474180: testing::TestCase::Run() (in /home/user/nvml/pmemkv/pmemkv/bin/pmemkv_test)
==4100==    by 0x47B25D: testing::internal::UnitTestImpl::RunAllTests() (in /home/user/nvml/pmemkv/pmemkv/bin/pmemkv_test)
==4100== 	Address: 0x285c05d0	size: 8	state: DIRTY
`

**Comment by RobDickinson** [comment]
obsolete
