### ISSUE TITLE
Put on btree crashes rather than returning FAILED

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#126]
If the btree engine runs out of space, a Put operation will throw an unhandled `std::bad_alloc` exception that results in a core dump.  The proper behavior here should be for Put to internally catch this exception and return FAILED.

We don't want C/C++ users to have to introduce catch handlers around every Put for all exception types for all engines, since that might be a big/changing list.  I don't think it's possible for FFI-based bindings to catch these exceptions at all.

**Comment by vinser52** [comment]
Fixed the issue
#129
