### ISSUE TITLE
bug in homepage code

### ISSUE THREAD

**Issue by yufeixiong** [pmem/pmemkv#128]
Hi, is there any bug in this code? 
It cannot be correctly compiled.
I believe that the functions "kvengine_put" and "kvengine_get" are not correctly called.
The code bellow is on home directory.

#include <libpmemkv.h>
#include <string.h>
#include <assert.h>

int main() {
    #define VAL_LEN 64
    char value[VAL_LEN];

    /* open the datastore */
    KVEngine* kv = kvengine_open("kvtree3", "/dev/shm/mykv", 8388608);

    /* put new key */
    int32_t len = strlen("value1");
    KVStatus s = kvengine_put(kv, "key1", "value1", &len);
    assert(s == OK);

    /* read last key back */
    len = VAL_LEN;
    s = kvengine_get(kv, "key1", VAL_LEN, value, &len);
    assert(s == OK && !strcmp(value, "value1"));

    /* close the datastore */
    kvengine_close(kv);

    return 0;
}

**Comment by RobDickinson** [comment]
Hi @yufeixiong, this example is old and doesn't match the current API.  I'll have an updated version posted tomorrow for you.  Thanks for raising this issue!

**Comment by RobDickinson** [comment]
Fixed as part of the cleanup in #130
