### ISSUE TITLE
stree2 engine (first non-experimental version)

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#145]
Produce an improved stree2 version that addresses these gaps:

* stree2 engine will support variable-length values (previously #81)
* stree2 engine will have explanation & diagrams on ENGINES.md page (previously #136)
* stree2 engine will be validated with valgrind (previously #124)
* when all of these are complete, show stree2 as stable engine on README.md page

**Comment by lukaszstolarczuk** [comment]
This is no longer valid. There are some stree issues, but these above are not the ones. There's still some work to make stree an non-experimental engine (at least: see `stree` label in issues).
