### ISSUE TITLE
Create man page

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#156]
Need a man page similar to other PMDK sub-libraries

**Comment by lukaszstolarczuk** [comment]
you'd like to see a man page generally for pmemkv or some more specific ones?

**Comment by RobDickinson** [comment]
@lukaszstolarczuk, I'm not sure.  Andy has mentioned several times that we should have man pages for pmemkv similar to the rest of PMDK, but we aren't providing any man pages for pmemkv yet.

**Comment by szyrom** [comment]
done
