### ISSUE TITLE
OutOfSpace tests failing with latest libpmemobj-cpp

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#157]
Haven't seen this before, these tests are passing in my Ubuntu environment...

```
[ RUN      ] KVTreeFullTest.OutOfSpace1Test
!!! creating cached copy at /tmp/pmemkv
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:788: Failure
Value of: kv->Put("100", "?") == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace1Test (8501 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace2aTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:796: Failure
Value of: kv->Put("100", LONGSTR) == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace2aTest (794 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace2bTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:806: Failure
Value of: kv->Put("100", LONGSTR) == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace2bTest (767 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace3aTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:813: Failure
Value of: kv->Put("100", LONGSTR) == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace3aTest (773 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace3bTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:821: Failure
Value of: kv->Put("123456", LONGSTR) == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace3bTest (771 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace4aTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:831: Failure
Value of: kv->Put(to_string(LARGE_LIMIT + 1), "1") == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace4aTest (762 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace4bTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:839: Failure
Value of: kv->Put(to_string(LARGE_LIMIT + 1), "1") == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace4bTest (785 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace5aTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:849: Failure
Value of: kv->Put(LONGSTR, "1") == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace5aTest (788 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace5bTest
```

**Comment by RobDickinson** [comment]
[ RUN      ] KVTreeFullTest.OutOfSpace1Test
!!! creating cached copy at /tmp/pmemkv
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:788: Failure
Value of: kv->Put("100", "?") == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace1Test (8501 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace2aTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:796: Failure
Value of: kv->Put("100", LONGSTR) == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace2aTest (794 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace2bTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:806: Failure
Value of: kv->Put("100", LONGSTR) == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace2bTest (767 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace3aTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:813: Failure
Value of: kv->Put("100", LONGSTR) == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace3aTest (773 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace3bTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:821: Failure
Value of: kv->Put("123456", LONGSTR) == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace3bTest (771 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace4aTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:831: Failure
Value of: kv->Put(to_string(LARGE_LIMIT + 1), "1") == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace4aTest (762 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace4bTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:839: Failure
Value of: kv->Put(to_string(LARGE_LIMIT + 1), "1") == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace4bTest (785 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace5aTest
/home/robfromboulder/pmemkv/tests/engines/kvtree_test.cc:849: Failure
Value of: kv->Put(LONGSTR, "1") == FAILED
  Actual: false
Expected: true
[  FAILED  ] KVTreeFullTest.OutOfSpace5aTest (788 ms)
[ RUN      ] KVTreeFullTest.OutOfSpace5bTest

**Comment by RobDickinson** [comment]
@lukaszstolarczuk are you seeing this problem with the Travis/CI environment?  (isn't that Fedora-based?)

**Comment by RobDickinson** [comment]
This appears to be caused by using the latest libpmemobj-cpp.  (I thought at first this was an Ubuntu vs Fedora issue, but it's actually that my Ubuntu workstation had an older libpmemobj-cpp version)

libpmemobj-cpp @ 41565ccdc25b675c229023743fef53be364e7a7c FAILS
libpmemobj-cpp @ 175f3650eb114085ba0ebcccaac8391fc8e7e3b6 SUCCEEDS

I'll dig into this further to see what's going on...

**Comment by lukaszstolarczuk** [comment]
I have on my machine libpmemobj-cpp at f0e194bbb87e4f6ea07ca050ce66a8e54e5f0be9 (Jan 25) and it looks good. I hope this'll help a little bit :)

**Comment by marcinslusarz** [comment]
Once I finally have managed to build pmemkv on my machine I bisected this regression to one of these 2 commits (with the first one pmemkv doesn't build):

pmem/libpmemobj-cpp@949646902dc170f6bae9d0522c230b187c4f22e9
pmem/libpmemobj-cpp@f6f2294f542b8715c16975552f7411cef311fc26

@igchor, @szyrom ?
