### ISSUE TITLE
Add test executions on HW/pmem

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmemkv#170]
It'd be a good option to execute (some) tests on HW (pmem)

details to be delivered...

**Comment by RobDickinson** [comment]
This is intended for 1.0, correct?

**Comment by szyrom** [comment]
@lukaszstolarczuk done?

**Comment by karczex** [comment]
https://github.com/pmem/pmemkv/pull/709 Is first PR to address this issue.

**Comment by lukaszstolarczuk** [comment]
I believe we can close this issue. Our Jenkins is mature enough and it checks the code on "real" HW.
