### ISSUE TITLE
Add possibility to `make` without tests execution

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmemkv#182]
I was asked today by our process team to add possibility in Makefile to make all without starting the tests execution.

**Comment by vinser52** [comment]
Does the 'make sharedlib' make what you want?

**Comment by lukaszstolarczuk** [comment]
it looks like reset and configure is also required for sharedlib

**Comment by marcinslusarz** [comment]
I think the main Makefile should be dropped completely. In some aspects it's incomplete, in others it's incorrect and everything it does correctly can be achieved with just cmake.

**Comment by RobDickinson** [comment]
What is being done incorrectly please?  All the top-level makefile is doing is providing a few aliases so there are fewer commands to type manually all the time.

**Comment by lukaszstolarczuk** [comment]
I never said it's harmful, what I meant is that if someone wants to run make without test execution they have to run command like `make reset configure sharedlib`, not something simple like `make [all]`

**Comment by RobDickinson** [comment]
@marcinslusarz can you please provide some specifics about what is incorrect in the build script?

**Comment by marcinslusarz** [comment]
This Makefile assumes that libraries are in $(prefix)/lib. Some distributions use $(prefix)/lib, but others use $(prefix)/lib64 or $(prefix)/lib/x86_64-linux-gnu. Using "cp" instead of "install" is also wrong, because $(prefix)/lib may not exist (e.g. when prefix=$HOME/pmemkv). 

Another (less severe) issue is that it touches directories outside of the build directory (/tmp and /dev/shm) without explicit user's action (like configuration). 

Once pmemkv will start using sonames, this Makefile will need to be extended to support it. Other installed files will need to be added too (documentation, pkg-config file, etc). New tests, examples will also require an update. There's no way to change the build type (by default it should use RelWithDebinfo btw).

This all can be fixed, but I think maintaining this Makefile is a waste of time.

**Comment by RobDickinson** [comment]
> This Makefile assumes that libraries are in $(prefix)/lib. Some distributions use $(prefix)/lib, but others use $(prefix)/lib64 or $(prefix)/lib/x86_64-linux-gnu. Using "cp" instead of "install" is also wrong, because $(prefix)/lib may not exist (e.g. when prefix=$HOME/pmemkv).

Thank you, this is very specific and should be logged as a defect.

> Another (less severe) issue is that it touches directories outside of the build directory (/tmp and /dev/shm) without explicit user's action (like configuration).

This is not really about the use of a top-level Makefile, but how our tests are implemented.

Our automated tests create files in /tmp and /dev/shm, and these files are fairly large, so the build is making sure that none of this is left around after the tests have completed.  How else to emulate persistent memory than to run against /dev/shm?

I have not heard a requirement before that a build system cannot create or remove files in /tmp or /dev/shm -- if this cannot be allowed for a case like this, then please open a defect.

>  New tests, examples will also require an update.

Examples and specialized tests are not present in this repository, but are in pmem/pmemkv-tools.

> There's no way to change the build type (by default it should use RelWithDebinfo btw).

This is not true.  Use of the top-level Makefile is not required.  You can always run a cmake build using whatever options you want.  The top-level Makefile does not restrict what you can do!

Having an easy path to run simple build commands does not prevent an advanced user like you from doing advanced things directly with cmake.  For example, the top-level Makefile doesn't itself support out-of-source builds, but you can still do this by using cmake directly.  Saying there is "no way" to change the build type to debug is incorrect.

> This all can be fixed, but I think maintaining this Makefile is a waste of time.

Believe me, you've made your point.  But the top-level aliases are not for a cmake expert like you who would prefer not to have any assistance.  The top-level aliases are for dumb people like me who just want to run the build & tests with a minimum to remember.
