### ISSUE TITLE
Shortcomings with "make install"

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#186]
This Makefile assumes that libraries are in $(prefix)/lib. Some distributions use $(prefix)/lib, but others use $(prefix)/lib64 or $(prefix)/lib/x86_64-linux-gnu. Using "cp" instead of "install" is also wrong, because $(prefix)/lib may not exist (e.g. when prefix=$HOME/pmemkv).

**Comment by ldorau** [comment]
It will be fixed by https://github.com/pmem/pmemkv/pull/232

**Comment by ldorau** [comment]
Fixed by #232
