### ISSUE TITLE
cmake does not inform about wrong libpmemobj version

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmemkv#195]
When old libpmemobj (e.g. 1.4) is installed our cmake reports "libpmemobj++/experimental/concurrent_hash_map.hpp not found (available in libpmemobj-cpp > 1.6"
even though the libpmemobj++ is in correct version (e.g. current master = 1.6-rc1-35).

It is because the minimal req. of obj++ is obj >=1.4, but the (experimental so far) hashmap in obj++ repo requires newer version of obj.

**Comment by igchor** [comment]
In libpmemobj-cpp we recently added options to disable certain experimental features (array/string/vector). Disabling means not installing the header files (and not building tests for those features). We plan to do the same for concurrent_hashmap. I think, in libpmemobj-cpp we could make required libpmemobj version dependent on required features. On current master, if concurrent_hashmap feature is enabled we could just require libpmemobj-cpp 1.6.

**Comment by szyrom** [comment]
done
