### ISSUE TITLE
Tweak pmemkv.h use of std::function parameters

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#201]
```
void KVEngine::All(const std::function<KVAllFunction> f) {
    auto localf = f;
    All(&localf, cb_all_function);
}
```

Can't we just change f to be non-const and have: All(&f, ...) and remove local variable?

```
void KVEngine::Get(const string& key, std::function<KVGetFunction> f) {
    std::function<KVGetFunction> localf = f;
```

I think this is not neccessary (we can just use f as it is passed by copy).

**Comment by vinser52** [comment]
In general, using std types in interface is a bad idea. It is error prone approach to pass std objects through module bundles. Because different modules can be compiled with different compilers (STL code is heavily inlined).

**Comment by igchor** [comment]
not applicable anymore
