### ISSUE TITLE
Tweaks to polymorphic_string.h

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#203]
* I think you do not have to use get_ro() everywhere, you can just write `is_pmem ? ...`
* ` pmem::obj::p<bool> is_pmem;` Using bool can be quite dangerous actually. C++ standard says that sizeof(bool) is implementation define. I would suggest using unsiged char which is guaranteed to have size == 1.
* Please remove dead code

**Comment by igchor** [comment]
No longer applicable
