### ISSUE TITLE
Tweaks to cmap.h

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#204]
* `#define LIBPMEMOBJ_CPP_USE_TBB_RW_MUTEX 1` Using a define (especially in header can cause some collisions with user code, which, after all, can use concurrent_hashmap independenlty). Maybe enabling TBB_MUTEX should not be done by define but rather by template parameter in hashmap? this should be changed in libpmemobj-cpp.
* ` static const size_t hash_multiplier = select_size_t_constant<2654435769U, 11400714819323198485ULL>::value;` What are those values? I would prefer having it as some kind of static const variable instead of just magic number.

**Comment by vinser52** [comment]
Using #define LIBPMEMOBJ_CPP_USE_TBB_RW_MUTEX 1 in internal header is OK. It impacts only PMEMKV compilation process. And has no impact to the user code.

**Comment by vinser52** [comment]
@igchor Can I close the issue? There are two parts. The part with hash multiplier was refactored.
As for #define LIBPMEMOBJ_CPP_USE_TBB_RW_MUTEX 1, we are doing this in internal header. It should not impact user code.

**Comment by igchor** [comment]
Ok, I agree about #define - I think it can be close.

**Comment by vinser52** [comment]
Issue was solved.
