### ISSUE TITLE
Tweaks to vsmap.cc

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#205]
> why pmem_string is used here instead of std::string with custom allocator (from memkind)?

> pmem_string is exactly std::string with PMEM C++ allocator from memkind.

> Okay, maybe the name should be different then? pmem_string is also alias for pmem::obj::experimental::string in polymorphic_string.h. And here the string is not really persistent, it just allocates data from pmem.

**Comment by vinser52** [comment]
Issue fixed in PR #243
