### ISSUE TITLE
Continuous Integration for bindings

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmemkv#221]
We need to include checks in CI for our bindings, so we know if we didn't break anything by changes in the main pmemkv repo

**Comment by lukaszstolarczuk** [comment]
@annamarcink is taking care of this issue

**Comment by lukaszstolarczuk** [comment]
#266 is solving first part of this

additionally we need to add compilation of examples (bindings' languages)

**Comment by lukaszstolarczuk** [comment]
#271 is solving second part of this :)

**Comment by szyrom** [comment]
Done
