### ISSUE TITLE
Memcached & Redis cmake file must not use hardcoded paths

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmemkv#244]
https://github.com/pmem/pmemkv/blob/master/cmake/redis-experimental.cmake
&
https://github.com/pmem/pmemkv/blob/master/cmake/memcached-experimental.cmake

must not contain hardcoded paths, we need to use more clever way to use these packages/libs

**Comment by lukaszstolarczuk** [comment]
partially fixed by #378

**Comment by lukaszstolarczuk** [comment]
we're planning on removal Caching engine along with next pmemkv release, so this issue will be then closed.

**Comment by karczex** [comment]
Caching engine was removed in c627171d7d5c2806a97ed81cf882455af16651b6
