### ISSUE TITLE
Missing API function getEnginesList

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmemkv#248]
We don't have a function returning currently available engines (something like getEnginesList). This may be in need when someone disable some engines and don't know which are available in currently build pmemkv

**Comment by lukaszstolarczuk** [comment]
@szyrom, @igchor, do we want this, finally?

**Comment by igchor** [comment]
I think it would be better to adjust return code from open if an engine is not enabled. Right now we just return failed and set errormsg to "unknown engine name". Instead, if someone specifies engine as "caching" and it is disabled we can return status NOT_SUPPORTED.

**Comment by szyrom** [comment]
agree with Igor

**Comment by igchor** [comment]
Additionaly we can return erromsg with list of all supported engines.

**Comment by lukaszstolarczuk** [comment]
partially covered in #390

**Comment by igchor** [comment]
I think, #390 is enough, I will close it.
