### ISSUE TITLE
Remove std data types from PMEMKV interface

### ISSUE THREAD

**Issue by vinser52** [pmem/pmemkv#252]
It is error prone to pass std objects between module bundles. Different modules could be compiled with different compilers and with different compiler options. Furthermore, STL code uses templates which are heavily inlined.

There are two ways to fix it:
*  in existing API we can change parameters to plain C types (std::string to char*, etc)
* if we are going to develop new interface. We can make it header only implementation. Such approach allows to use STL data types as parameters. Furthermore, we can get rid of std::function as a callback type argument and just make it template parameter which allows to accept any functor objects and lambdas.

**Comment by igchor** [comment]
Is this really a problem? I think when you use different compilers (different for user program than for pmemkv) it is ok as long as you use the same standard library implementation. And I think it's reasonable to assume/enforce that the same stdlib is used.

**Comment by vinser52** [comment]
STL containers are class templates. It means the code is in headers. If two modules compiled with different versions for C++ library, the data structures could have different layout in different versions of C++ library. ABI interface is not the same in this case.

After googling I found the following link with explanations: https://stackoverflow.com/questions/17885060/passing-reference-to-stl-vector-over-dll-boundary/17924465#17924465

**Comment by igchor** [comment]
We also had an idea of not exporting C++ symbols - just "C" ones. The interface for C++ would then be header only implementation (as you suggested) and build on top of that "C" functions.

**Comment by igchor** [comment]
I have created PR which implements something like that: https://github.com/pmem/pmemkv/pull/265

One drawback of this approach is that we cannot easily use std::function as callback type i C++ interface (we wouldn't be allowed anyway, as this is std type). My suggestion is to create our implementation of callable object - a "function_view". We would export this symbol next to "C" ones and use in C++ interface.

**Comment by igchor** [comment]
As our C++ implementation is now header only this is no longer an issue
