### ISSUE TITLE
All dangerous work from engines destructor should be moved to Stop() method.

### ISSUE THREAD

**Issue by igchor** [pmem/pmemkv#258]
Currently if some exception happen during cleanup - application is aborted (exception inside of destructor). If we move dangerous work to Stop() method then we can catch that exception and try to recover.

**Comment by szyrom** [comment]
we should provide helper function flush() or sync() if an engine will need this before closing (if closing might be dangerous)

**Comment by szyrom** [comment]
Policy have changed - there are no engines that do dangerous work on DB close.
