### ISSUE TITLE
Default implementation of AllAbove, AllBelow, etc. should throw "not implemented" exception.

### ISSUE THREAD

**Issue by igchor** [pmem/pmemkv#261]

**Comment by vinser52** [comment]
Interesting suggestion. Maybe base class for all methods should provide implementations which just throw "not implemented"?

**Comment by igchor** [comment]
I was thinking about range query APIs but actually you're right, every method can have such default implementation.

**Comment by szyrom** [comment]
covered in https://github.com/pmem/pmemkv/issues/285
