### ISSUE TITLE
TOCTOU vulnerability in Start method

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmemkv#275]
In libpmemkv.cc in Start method we have vulnerability to TOCTOU bugs

```
if ((stat(path, &info) < 0) || !S_ISDIR(info.st_mode)) {
    throw runtime_error("Config path is not an existing directory");
}
return new vsmap::VSMap(context, path, size);
```
We should check if it is a dir right before use (within engine code) rather then here.

Reported by @marcinslusarz

**Comment by ldorau** [comment]
see Klocwork issue no 47

**Comment by szyrom** [comment]
done
