### ISSUE TITLE
Create linker script to export only C API symbols.

### ISSUE THREAD

**Issue by igchor** [pmem/pmemkv#281]
We can do it similarly as in: https://github.com/pmem/pmemfile/blob/master/src/libpmemfile-posix/CMakeLists.txt

**Comment by marcinslusarz** [comment]
FTR, in vmemcache it's a bit simpler: https://github.com/pmem/vmemcache/blob/master/src/CMakeLists.txt#L60, because it doesn't ship static libraries. But I think listing symbols in CMakeLists.txt (like in pmemfile) is better because it will simplify potential Windows port.

**Comment by szyrom** [comment]
https://github.com/pmem/pmemkv/commit/1a3f30900ef3fa2e4cd4518df3d8a60ff6a6d46f
done
