### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by igchor** [pmem/pmemkv#285]
Currently only some methods return pmemkv_status. We have no way of knowing whether AllAbove failed or is not supported by engine or there are no elements.

We could return status in all methods (in case of count, negative values could mean error).

**Comment by szyrom** [comment]
merged with https://github.com/pmem/pmemkv/issues/270

**Comment by szyrom** [comment]
merged with https://github.com/pmem/pmemkv/issues/261

Default implementation of AllAbove, AllBelow, etc. should throw "not implemented" exception.

**Comment by szyrom** [comment]
merged with https://github.com/pmem/pmemkv/issues/256

Add pmemkv_errormsg function. This function would provide more information (than KVStatus) about a failure.

**Comment by lukaszstolarczuk** [comment]
As pointed by Marcin in #188, in vcmap_test.cc we're using `pmemobj_errormsg()`, which should not take place. With this issues we should also fix such occurrences.
