### ISSUE TITLE
must not download googletest from the network

### ISSUE THREAD

**Issue by kilobyte** [pmem/pmemkv#296]
Current build system downloads googletest from the network at build (not even configure) time.  This is an absolute no-no for distributions — packages may use only packaged build-dependencies.

At the very least, the build system must support using system-installed googletest.  But then, I don't see why this dependency should be any different from the others (libpmemobj-cpp, tbb, memkind, rapidjson, ...) — let's just drop the download.  All current distributions have gtest 1.8.1, while RHEL and SLES can cope.

**Comment by lukaszstolarczuk** [comment]
this is probably a good idea to fix this in pmemkv-jni repo as well

**Comment by xuning97** [comment]
While using pmemkv in MemVerge, I encountered the same issue.

So I switched to Catch2, it's just a header file.

And one benefit is that catch2 can support some level of benchmark directly in its test case.

https://github.com/catchorg/Catch2/blob/master/docs/benchmarks.md#top

Microbenchmarking is very useful for our cases.

**Comment by xuning97** [comment]
Any possibility to use catch2, which seems simpler. But there could be a lot of changes in test module.

**Comment by kilobyte** [comment]
Crudely hacking in `libgtest-dev` 1.8.1-3 (from Debian, but other dists have same) instead of downloaded 1.7 passes all the tests.  Might be enough for a lazy distro maintainer for now.

```
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index 3e0f4ae..80fc4b1 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -135,12 +135,12 @@ if(ENGINE_TREE3)
        list(APPEND TEST_FILES engines-experimental/tree3_test.cc)
 endif()
 
-include(gtest)
+#include(gtest)
 include(get_tests.cmake)
 
 add_executable(pmemkv_test ${TEST_FILES})
 
-target_link_libraries(pmemkv_test pmemkv libgtest ${CMAKE_DL_LIBS})
+target_link_libraries(pmemkv_test pmemkv libgtest.a -pthread ${CMAKE_DL_LIBS})
 if(ENGINE_CACHING)
        target_link_libraries(pmemkv_test memcached)
 endif()
```

**Comment by szyrom** [comment]
@xuning97 what will be the benefit for using catch2?

**Comment by xuning97** [comment]
catch2 is a single header file lib, no need to link to so.
One other benefit is its builtin benchmark macro, which could be useful.

It's also a good idea to use gtest with refined CMakeLists.txt, since pmemkv already has many tests written in it.

**Comment by lukaszstolarczuk** [comment]
We've picked an option to use gtest from distros for now. It's an easy solution and should be enough for us. For now we don't see catch2 bringing us very much additions (and it is costly to introduce it in pmemkv), but we don't say it may not change in the future...
