### ISSUE TITLE
improve handle errors from engine constructors

### ISSUE THREAD

**Issue by igchor** [pmem/pmemkv#302]
Currently, most engine methods catch all possible exceptions and return status. In constructor, if some exception occurs it is propagated to pmemkv_open method - this is not consistent. 

To return meaningful error (status) from pmemkv_open we would have to create some custom exceptions (or throw status instance?), catch them in pmemkv_open and translate to proper status. 

Another option is to create status open(pmemkv_config *config)  method in engine and make constructor take no parameters. This way we can have consistent behavior and return status. However this makes it more difficult to write engines - all variables in engine must be default-constructible (there is only default constructor for an engine).

**Comment by kilobyte** [comment]
At least within our tests, error reporting **sucks**.  You don't even know if pool creation due to disk full or another process using the same pool.
