### ISSUE TITLE
Each() vs All()

### ISSUE THREAD

**Issue by igchor** [pmem/pmemkv#303]
Currently we have 2 very similar families of functions:
`all(), all_above(), all_below(), all_between()` and `each(), each_above(), each_below(), each_between()`.  The difference between them is that `all` functions iterates only over keys in database while `each` functions iterate over key and value.

Currently, we do not have any engine which can make iteration over keys much faster than over keys and value. That's why I don't see any benefit in keeping both `all` and `each` functions. Maybe we could only have `each` family (key and value)?

**Comment by RobDickinson** [comment]
The benefit comes from being able to choose how much data is copied over JNI/FFI or similar.  You can burn a lot of time copying large values if they are not needed.

**Comment by igchor** [comment]
Right, copying value in bindings can be costly but why are we exposing those functions in C/C++ interface? We could probably implement `each` and `all` in bindings on top of 'each' method (if we would do that in JNI for example, we would only pay the price for copying pointer and size of value)

**Comment by RobDickinson** [comment]
That's true -- I had hoped that an engine like kvtree (that stores all keys in dram anyway) would be able to satisfy `all` without accessing persistent memory, but never got around to implementing that change.  Currently the only benefit is in the bindings.

The thinking at the time was that if the user only needs key data, that seemed like a good place to allow optimizations at the engine or binding level.  Up to you whether you want to allow those possibilities or not.  If value data gets really big, reading those values from persistent memory will add significant latency compared to small keys.  (and even faster if keys are cached in memory)

**Comment by lukaszstolarczuk** [comment]
changed in #325 
but we need to update bindings repos
