### ISSUE TITLE
Remove PMEMKV_STATUS_FAILED

### ISSUE THREAD

**Issue by igchor** [pmem/pmemkv#394]
This status is too generic. It is not possible to handle it correctly from the application.
We should replace it with something like PMEMKV_STATUS_UNSPECIFIED_ERROR or PMEMKV_STATUS_WTF and suggests users to use ret != PMEMKV_STATUS_OK to check if there were any erros.

We should also remove uses of PMEMKV_FAILED in current code.

**Comment by lukaszstolarczuk** [comment]
partially covered in #396
