### ISSUE TITLE
Add CMake flag TESTS_USE_FORCED_PMEM

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmemkv#477]

**Comment by lukaszstolarczuk** [comment]
Changed approach to not use an additional CMake flag, but rather add info on how to set up PMDK's PMEM_IS_PMEM flag in a testing environment.
Implemented in #514

**Comment by igchor** [comment]
Covered in: https://github.com/pmem/pmemkv/pull/617
