### ISSUE TITLE
Broken image in README

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#48]
Still using the broken version where "Value48" is repeated

**Comment by RobDickinson** [comment]
Here's the fixed version:

![pmemkv1](https://cloud.githubusercontent.com/assets/913363/25543024/289f06d8-2c12-11e7-86e4-a1f0df891659.png)

**Comment by szyrom** [comment]
![pmemkv_design_diagram](https://user-images.githubusercontent.com/12031346/60339348-d181a200-99a8-11e9-96a6-d145ac010185.png)
