### ISSUE TITLE
Make the library, and tests less dependent on a specific revision of pmemobj

### ISSUE THREAD

**Issue by GBuella** [pmem/pmemkv#50]
Relying on a specific version of pmemobj results in such constructs in pmemkv_test:

```
const int LARGE_LIMIT = 6012299;
```
Since the cmake build already uses whatever version of pmemobj it finds using pkg-config, this can be a problem. Having the "wrong" version of pmemobj after doing a cmake build can result in such errors:
```
$ ./pmemkv_test --gtest_filter=KVTest.LargeAscendingTest
Note: Google Test filter = KVTest.LargeAscendingTest
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from KVTest
[ RUN      ] KVTest.LargeAscendingTest
/home/tej/code/pmemkv/src/pmemkv_test.cc:747: Failure
Value of: kv->Put(istr, (istr + "!")) == OK
  Actual: false
Expected: true
out of memory
[  FAILED  ] KVTest.LargeAscendingTest (26001 ms)
```

**Comment by RobDickinson** [comment]
Between these changes and those in #55, I think we're in good shape here.

@GBuella, I really like the approach you took to solve this problem versus the ugly pattern of hard-coding magic sizes everywhere. Thanks so much for the contribution!
