### ISSUE TITLE
Add get_between and get_above API for stree engine

### ISSUE THREAD

**Issue by JerryYangSH** [pmem/pmemkv#521]
I can implement it if no one plans to work on it

**Comment by szyrom** [comment]
@JerryYangSH 
you are more than welcome to implement it! And we will be more than happy to help you if there will be any questions

**Comment by JerryYangSH** [comment]
@szyrom Could you please grant me access to the repo?  I got 403 error when trying to push my commit.
jerry@u19:~/opensources/pmemkv$ git push --set-upstream origin pmemkv-stree-get-above
Username for 'https://github.com': JerryYangSH
Password for 'https://JerryYangSH@github.com':
remote: Permission to pmem/pmemkv.git denied to JerryYangSH.
fatal: unable to access 'https://github.com/pmem/pmemkv.git/': The requested URL returned error: 403

**Comment by igchor** [comment]
@JerryYangSH we accept contributions via Pull Requests, please see https://github.com/pmem/pmemkv/blob/master/CONTRIBUTING.md for details. You do not need push access to make a PR.

**Comment by szyrom** [comment]
@JerryYangSH can you ping me at szymon.romik@intel.com? I have some questions but couldn't find any information about how to contact you directly. Thanks!

**Comment by JerryYangSH** [comment]
@szyrom I have sent you mail by 20830326@qq.com.Thanks.

**Comment by lukaszstolarczuk** [comment]
Implemented in #523.
Thanks! I'm closing this issue.
