### ISSUE TITLE
Support binary-safe keys

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#53]
Although `pmemkv` doesn't prevent binary data in key strings, we're using `strcmp` internally to compare keys (which leads to bad results if a null char appears in the middle of a key string).

**Comment by krzycz** [comment]
Does "reject" means "truncate"?

**Comment by RobDickinson** [comment]
Hi @krzycz, think of this issue as a placeholder.  There's no question that we should support binary-safe values, which is currently working.  We need to decide if we'll allow binary-safe keys as well (in which case we need to quit using `strcmp` to compare keys), or if we are going to disallow binary data in keys and what that looks like to the caller.

Now you might reasonably ask -- why even debate at all, do we really care what data is used for keys?  Not sure, but maybe.  We have lots of ideas around key partitioning and ranges where we'd be inspecting keys and assigning policies based on string matches.

In any case, there's some change here that needs to be worked out, but this issue might get a new title and description as we debate exactly what to do.

**Comment by krzycz** [comment]
I would opt for allowing binary-safe keys.
I thought it would also help with non-UTF8 strings (i.e. there could be zero bytes in  UTF16-encoded string), but that's a different story.
As for key partitioning, it would be easier if we could discuss it on some example. I remember there were some ideas, but I'm not sure how are they affected by the support for binary-safe strings.

**Comment by lplewa** [comment]
Maybe you should to convert keys to base64 format(or similar), it might create other problems (keys will be bigger, conversion takes time etc..) but it resolve \0 byte issue.

**Comment by krzycz** [comment]
Interesting idea...
The keys are bigger, but it's easy to calculate the output string length, assuming you know the length in bytes of the input key. 
Performance could be a problem, I'm afraid, as you need to do the conversion each time (for each SET and GET). Also, you can't do the partial key matching easily (i.e. get all the keys containing some pattern) w/o decoding each key. (But if you only need to look up for keys starting with some pattern, you can do it on encoded data. At least, you can filter out 99% of the keys that do not match).

**Comment by RobDickinson** [comment]
Prakash at Dynox made a great case for binary-safe keys:  namely use-cases where the key is a serialized object over which you have no control over the formatting.  (such as using a serialized Java object as a key).  So I'm switching the intent of this ticket to fully support binary-safe keys.

**Comment by RobDickinson** [comment]
This will be included in the final version of `kvtree2`

**Comment by RobDickinson** [comment]
Rolled up as part of #80
