### ISSUE TITLE
memkind-based engines returns UNKNOWN_ERROR for wrong path/size in config

### ISSUE THREAD

**Issue by karczex** [pmem/pmemkv#565]
vsmap and vsmap returns PMEMKV_STATUS_UNKNOWN_ERROR for wrong path in config instead of PMEMKV_STATUS_INVALID_ARGUMENT.  

Test:  https://github.com/pmem/pmemkv/pull/564/commits/26d3d628f39155f2c565ed4f7eee430251051fcb 
Log: [NonExistingPath.log](https://github.com/pmem/pmemkv/files/3997870/NonExistingPath.log)

**Comment by igchor** [comment]
Actually not only vsmap/vcmap return wrong error, cmap also is affected.

**Comment by igchor** [comment]
We could also extend engines tests with non-existent paths, with some corner case like you suggested in https://github.com/pmem/pmemkv/pull/722 (for configs) : ```" ", "", "//",
					  ",./;'[]-=<>?:\"{}|_+!@#$%^&*()`~", "/👾"
```

**Comment by JanDorniak99** [comment]
For now, it's only possible to check the reason for failure only in pmemobj based engines. In volatile engines I believe we don't have this option due to limitations in memkind's error handling

**Comment by lukaszstolarczuk** [comment]
we could ask @michalbiesek for new feature, regarding the error handling in memkind.

**Comment by michalbiesek** [comment]
Regarding memkind and error handling by functions `memkind_create_pmem_with_config` or `memkind_create_pmem`, for example in following cases:

- size is smaller than MEMKIND_PMEM_MIN_SIZE 
- trying to create a pool in a path that doesn't exist

The above functions will return the status MEMKIND_ERROR_INVALID provided in memkind.h - I am not sure how it affects your engines, could you please clarify the issue here.

**Comment by igchor** [comment]
@michalbiesek I think the problem is that this information is lost on the C++ layer (pmem_alloctor). I think, that we translate all errors to std::runtime_error. Maybe we could add some memkind-specific exceptions (which would correspond to statuses)?

**Comment by KFilipek** [comment]
> @michalbiesek I think the problem is that this information is lost on the C++ layer (pmem_alloctor). I think, that we translate all errors to std::runtime_error. Maybe we could add some memkind-specific exceptions (which would correspond to statuses)?

It's problem with code I've previously talked (src/pmemobj_engine.h).
@michalbiesek Please see that PR #942 solve this issue.

**Comment by igchor** [comment]
@KFilipek that code is for pmemobj only, for memkind we use https://github.com/memkind/memkind/blob/master/include/pmem_allocator.h . And I think pmem_allocator would be the best place to extend with regard to error handling. Of course we would have to add extra code to pmemkv anyway (right now, we just have no way to do that from C++)

**Comment by michalbiesek** [comment]
@igchor 
Sure feel free to open Issue or even better Pull Request, since you probably know what exception would be best here. Not sure if you want to distinguish the cases mentioned above but this would require additional changes on the memkind layer.

**Comment by KFilipek** [comment]
> @michalbiesek I think the problem is that this information is lost on the C++ layer (pmem_alloctor). I think, that we translate all errors to std::runtime_error. Maybe we could add some memkind-specific exceptions (which would correspond to statuses)?

Specific engine should take care about what he passes to underlying classes, methods etc. I don't see any checks under vsmap. Making separate exception for a dependency is wrong way I think.

**Comment by igchor** [comment]
What checks? You suggest to do all the checks memkind does ourselves? That would be logic duplication and the number of requirements for memkind parameters can grow (which would mean we would need to add new checks in future).

**Comment by KFilipek** [comment]
I suggest that engine backend should take care what passes to underlying layers. Currently engine like vsmap just passes everything in a blind way.

**Comment by igchor** [comment]
The memkind C++ allocator should provide more detailed information about error - and it's usefull not only for pmemkv but for all users. @michalbiesek do you think we could create memkind-specific exceptions like invalid_argument_exception and throw it from pmem_allocator ctor? The only extra logic would be to throw appropriate exception, right?

We would have something like this:
```
int err_c  = memkind_create_pmem_with_config(cfg, &kind);
if (err_c == MEMKIND_ERROR_INVALID) throw memkind::invalid_exception();
else if (err_c) throw std::runtime_error();
```

**Comment by igchor** [comment]
@KFilipek but why duplicate the checks and not rely on the lower layer is the checks are already there? (and we have the appropriate info, it's just lost in C++)

**Comment by michalbiesek** [comment]
> The memkind C++ allocator should provide more detailed information about error - and it's usefull not only for pmemkv but for all users. @michalbiesek do you think we could create memkind-specific exceptions like invalid_argument_exception and throw it from pmem_allocator ctor? The only extra logic would be to throw appropriate exception, right?
> 
> We would have something like this:
> 
> ```
> int err_c  = memkind_create_pmem_with_config(cfg, &kind);
> if (err_c == MEMKIND_ERROR_INVALID) throw memkind::invalid_exception();
> else if (err_c) throw std::runtime_error();
> ```

From my perspective, it looks ok, @igchor you will be able to create PR for it?

**Comment by igchor** [comment]
Ok, I'm not sure if we will manage to do this right away but we will certainly plan it.
