### ISSUE TITLE
Add create_if_missing option to config

### ISSUE THREAD

**Issue by karczex** [pmem/pmemkv#576]
It would be useful to add to config option to create pool if not exists, or just open if exists. Let's name it 'soft_create' or 'create_if_not_exists'.  
Currently if user is able to create pool due to OS configuration, he cannot just read config from file and apply it . Instead he have to check if file exists and modify config accordingly, like in this python snippet: 
``` 
if not os.path.exists(config['path']):
    config[force_create]  = 1
```

**Comment by igchor** [comment]
If you need to have this kind of logic in your app then your code snippet is exactly how it should be handled. We cannot do this in pmemkv because path can be anything - /dev/dax (always exists), path to a file or path to a poolset. To have this feature we would need obj support.

**Comment by karczex** [comment]
rocksdb implements create_if_missing option: 

```c++
#include <assert>
#include "rocksdb/db.h"

rocksdb::DB* db;
rocksdb::Options options;
options.create_if_missing = true;
rocksdb::Status status =
  rocksdb::DB::Open(options, "/tmp/testdb", &db);
```

snippet from: https://rocksdb.org/docs/getting-started.html

**Comment by igchor** [comment]
Ok, we should add create_if_missing option which can be implemented as:

```
int err = pmemobj_create()
if (err != 0) return pmemobj_open()
```

We can also create an error_is_exists alias for `force_create` to be consistent with rocksDB
