### ISSUE TITLE
vcmap__error_handling_oom_0__none test fails

### ISSUE THREAD

**Issue by igchor** [pmem/pmemkv#623]
This test is introduced in https://github.com/pmem/pmemkv/pull/617

I have made a reprocuder (with only tbb in version 2019~U8-1) and it looks like this binary fails (with segfault) only when all of following are true:
* compiled with clang (I tested on clang-9.0.0-2)
* linked with libunwind (version 1.2.1-9)
* compiled with -O2

 I'm not sure where is the problem yet.

```
#include <sys/time.h>
#include <sys/resource.h>

#include <iostream>

#include <tbb/concurrent_hash_map.h>

#include <dlfcn.h>
#include <stdio.h>

#define MB (1024 * 1024)
#define HEAP_LIMIT_SIMULATE (100 * MB)

typedef tbb::concurrent_hash_map<std::string, std::string,
			 tbb::tbb_hash_compare<std::string>> map_t;

int main(int argc, char *argv[])
{
	const struct rlimit heap_limit = { HEAP_LIMIT_SIMULATE, HEAP_LIMIT_SIMULATE };
	auto err = setrlimit(RLIMIT_DATA, &heap_limit);
	if (err) {
		fprintf(stderr, "Unable to set heap limit.\n");
		return 1;
	}

	map_t map;

	size_t cnt = 0;
	while (1) {
		try {
			map_t::value_type kv_pair{
					std::to_string(cnt),
					std::string(cnt + 1, 'a')};

			map.insert(kv_pair);
		} catch (std::bad_alloc &) {
			std::cout << "OOM at " << cnt << std::endl;
			return 1;
		}


		cnt++;
	}

	return 0;
}
```

**Comment by szyrom** [comment]
probably to verify by @vinser52 ?

**Comment by karczex** [comment]
I was able to reproduce this issue only with libunwind in version from ubuntu repository (19.10 and 20.04)  

Cannot reproduce with libunwind 1.2.1 (or newer) built from source.

**Comment by igchor** [comment]
Closing since not reproducible on newer versions
