### ISSUE TITLE
SLES12SP4 build error need help after use c++14

### ISSUE THREAD

**Issue by gwnet** [pmem/pmemkv#629]
murray-rust:/tmp/wayne/pmem/pmemkv/build # cmake  -D CMAKE_C_COMPILER=/usr/bin/gcc-6 -D CMAKE_CXX_COMPILER=/usr/bin/g++-6 ..
-- CMAP engine is ON
-- VCMAP engine is OFF
-- VSMAP engine is ON
-- CACHING engine is OFF
-- STREE engine is OFF
-- TREE3 engine is OFF
-- Configuring done

urray-rust:/tmp/wayne/pmem/pmemkv/build # sudo make
Scanning dependencies of target checkers
[  0%] Built target checkers
Scanning dependencies of target pmemkv
[  6%] Building CXX object CMakeFiles/pmemkv.dir/src/libpmemkv.cc.o
[ 13%] Building CXX object CMakeFiles/pmemkv.dir/src/engine.cc.o
[ 20%] Building CXX object CMakeFiles/pmemkv.dir/src/engines/blackhole.cc.o
[ 26%] Building CXX object CMakeFiles/pmemkv.dir/src/out.cc.o
[ 33%] Building CXX object CMakeFiles/pmemkv.dir/src/engines/cmap.cc.o
[ 40%] Building CXX object CMakeFiles/pmemkv.dir/src/engines/vsmap.cc.o
In file included from /usr/include/c++/6/tuple:40:0,
                 from /usr/include/c++/6/functional:55,
                 from /tmp/wayne/pmem/pmemkv/src/engines/../engine.h:36,
                 from /tmp/wayne/pmem/pmemkv/src/engines/vsmap.h:35,
                 from /tmp/wayne/pmem/pmemkv/src/engines/vsmap.cc:33:
/usr/include/c++/6/bits/uses_allocator.h: In instantiation of 'struct std::__uses_alloc<true, const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::scoped_allocator_adaptor<libmemkind::pmem::allocator<std::_Rb_tree_node<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > > > >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >&&>':
/usr/include/c++/6/scoped_allocator:369:57:   required from 'void std::scoped_allocator_adaptor<_OuterAlloc, _InnerAllocs>::construct(std::pair<_U1, _U2>*, std::piecewise_construct_t, std::tuple<_Args2 ...>, std::tuple<_Args2 ...>) [with _T1 = const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >; _T2 = std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >; _Args1 = {std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >&&}; _Args2 = {}; _OuterAlloc = libmemkind::pmem::allocator<std::_Rb_tree_node<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > > >; _InnerAllocs = {}]'
/usr/include/c++/6/bits/alloc_traits.h:243:4:   required from 'static std::_Require<typename std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::type> std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > >; _Args = {const std::piecewise_construct_t&, std::tuple<std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >&&>, std::tuple<>}; _Alloc = std::scoped_allocator_adaptor<libmemkind::pmem::allocator<std::_Rb_tree_node<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > > > >; std::_Require<typename std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::type> = void]'
/usr/include/c++/6/bits/alloc_traits.h:344:16:   required from 'static decltype (std::allocator_traits<_Alloc>::_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > >; _Args = {const std::piecewise_construct_t&, std::tuple<std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >&&>, std::tuple<>}; _Alloc = std::scoped_allocator_adaptor<libmemkind::pmem::allocator<std::_Rb_tree_node<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > > > >; decltype (std::allocator_traits<_Alloc>::_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = void]'
/usr/include/c++/6/bits/stl_tree.h:543:32:   required from 'void std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_construct_node(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type, _Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >&&>, std::tuple<>}; _Key = std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >; _Val = std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > >; _KeyOfValue = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > >; _Compare = std::less<std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > >; _Alloc = std::scoped_allocator_adaptor<libmemkind::pmem::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > >*]'
/usr/include/c++/6/bits/stl_tree.h:560:4:   required from 'std::_Rb_tree_node<_Val>* std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_create_node(_Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >&&>, std::tuple<>}; _Key = std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >; _Val = std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > >; _KeyOfValue = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > >; _Compare = std::less<std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > >; _Alloc = std::scoped_allocator_adaptor<libmemkind::pmem::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > >*]'
/usr/include/c++/6/bits/stl_tree.h:2196:64:   required from 'std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_emplace_hint_unique(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator, _Args&& ...) [with _Args = {const std::piecewise_construct_t&, std::tuple<std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >&&>, std::tuple<>}; _Key = std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >; _Val = std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > >; _KeyOfValue = std::_Select1st<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > >; _Compare = std::less<std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > >; _Alloc = std::scoped_allocator_adaptor<libmemkind::pmem::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator = std::_Rb_tree_iterator<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator = std::_Rb_tree_const_iterator<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > >]'
/usr/include/c++/6/bits/stl_map.h:502:8:   required from 'std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](std::map<_Key, _Tp, _Compare, _Alloc>::key_type&&) [with _Key = std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >; _Tp = std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >; _Compare = std::less<std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > >; _Alloc = std::scoped_allocator_adaptor<libmemkind::pmem::allocator<std::pair<const std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >, std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> > > > >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = std::basic_string<char, std::char_traits<char>, libmemkind::pmem::allocator<char> >]'
/tmp/wayne/pmem/pmemkv/src/engines/vsmap.cc:307:66:   required from here
/usr/include/c++/6/bits/uses_allocator.h:89:7: error: static assertion failed: construction with an allocator must be possible if uses_allocator is true
       static_assert(__or_<
       ^~~~~~~~~~~~~
CMakeFiles/pmemkv.dir/build.make:144: recipe for target 'CMakeFiles/pmemkv.dir/src/engines/vsmap.cc.o' failed
make[2]: *** [CMakeFiles/pmemkv.dir/src/engines/vsmap.cc.o] Error 1
CMakeFiles/Makefile2:181: recipe for target 'CMakeFiles/pmemkv.dir/all' failed
make[1]: *** [CMakeFiles/pmemkv.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by igchor** [comment]
Fixed: https://github.com/pmem/pmemkv/pull/641
