### ISSUE TITLE
Exceptions specific to the engine shouldn't be caught in libpmemkv.cc

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmemkv#650]
We should not add dependency to "libpmemobj++/pexceptions.hpp" in libpmemkv.cc. It's needed in this line: https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L56
but it may not be needed if all libpmemob_based engines are turned offf.

ref. https://github.com/pmem/pmemkv/pull/522#issuecomment-554282808

**Comment by szyrom** [comment]
we should always require libpmemobj-cpp and modify our CMake files

**Comment by lukaszstolarczuk** [comment]
It was finally closed in the #522 - CMake and docs were updated.
