### ISSUE TITLE
Set valuebytes to value size in KVTree::Get even if value size is greater than limit -1

### ISSUE THREAD

**Issue by SinghalB** [pmem/pmemkv#66]
This will enable applications to call KVTree::Get again with correct limit and buffer to hold the value if the size of value is not known.

<pre>
 KVStatus KVTree::Get(const string& key, const int32_t limit, char* value, int32_t* valuebytes) {
     LOG("Get for key=" << key.c_str());
     auto leafnode = LeafSearch(key);
     if (!leafnode) {
         LOG("   head not present");
@@ -115,23 +115,24 @@ KVStatus KVTree::Get(const string& key, const int32_t limit, char* value, int32_
             if (strcmp(leafnode->keys[slot].c_str(), key.c_str()) == 0) {
                 auto kv = leafnode->leaf->slots[slot].get_ro();
                 auto vs = kv.valsize();
+                *valuebytes = vs;
                 if (vs < limit - 1) {
                     LOG("   found value, slot=" << slot << ", size=" << to_string(vs));
                     memcpy(value, kv.val(), vs);
-                    *valuebytes = vs;
                     return OK;
                 } else {
                     return FAILED;
                 }
             }
         }
     }
     LOG("   could not find key");
     return NOT_FOUND;
 }
</pre>

**Comment by RobDickinson** [comment]
Hi @SinghalB, let me think about this a little more, but seems like a great suggestion!

**Comment by SinghalB** [comment]
Hi @RobDickinson 

I have also noticed that sometimes Get (w/ limit) returns -1 when value size is zero even though enough buffer is available.

What is the behaviour if I put a key with empty value?

Regards,
Bhaskar

**Comment by RobDickinson** [comment]
Included in the final version of `kvtree2`

**Comment by RobDickinson** [comment]
Rolled up as part of #80
