### ISSUE TITLE
vcmap__concurrent_put_get_remove_single_op_params fails

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmemkv#699]
# ISSUE:
vcmap__concurrent_put_get_remove_single_op_params fails

## Environment Information
- pmemkv version(s): master                                                
- libpmemobj-cpp version(s): master                                         
- PMDK (libpmem/libpmemobj) package version(s): 1.8                      
- OS(es) version(s): Fedora 31, OpenSuse Leap, ArchLinux (?)

## Please provide a reproduction of the bug:

`ctest -R vcmap__concurrent_put_get_remove_single_op_params --output-on-failure`

## How often bug is revealed:
sometimes: rare to often

## Actual behavior:

[fail___vcmap__concurrent_put_get_remove_single_op_params__default_1000_0_memcheck.txt](https://github.com/pmem/pmemkv/files/4688710/fail___vcmap__concurrent_put_get_remove_single_op_params__default_1000_0_memcheck.txt)

**Comment by karczex** [comment]
Issue is resolved by https://github.com/pmem/pmemkv/pull/749
