### ISSUE TITLE
New storage engine based on persistent B+tree

### ISSUE THREAD

**Issue by vinser52** [pmem/pmemkv#71]
We have created prototype of persistent B+tree using copy-on-write approach. On a write benchmark its outperform default PMEMKV storage engine. This issue is created to integrate persistent B+tree as a storage engine to PMEMKV

**Comment by RobDickinson** [comment]
Hi @vinser52, I merged your pull request and then made just a few tweaks as per #72.  The merged & updated code requires the most recent PMDK (where the old `nvml` namespace has been deprecated in favor of the new `pmem` namespace).  I think this initial integration is complete, please close if you agree.  Can't wait to try this against `kvtree` and `kvtree2` on real hardware!
