### ISSUE TITLE
Lack of dependencies in RPM generated by buildsystem 

### ISSUE THREAD

**Issue by karczex** [pmem/pmemkv#768]
# ISSUE:  Lack of dependencies in RPM generated by buildsystem 
## Environment Information

- pmemkv version(s):                                                 1e96af05d6790258ac003e4449cd4f69c039f09a 
- dependencies as defined in Docker images for this commit

## Please provide a reproduction of the bug:

Build rpm from sources:
```sh
cmake -DCPACK_GENERATOR=RPM ..
make package
rpm -pqR libpmemkv-devel-1.2-*.rpm
```

## How often bug is revealed:

always

## Actual behavior:
 ```
rpm -pqR libpmemkv-devel-1.2-*.rpm
/bin/sh
/bin/sh
/bin/sh
/bin/sh
libpmemobj >= 1.8
memkind >= 1.8.0
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
tbb
```

## Expected behavior:

Similarly to pmemkv package from fedora repository  libpmemobj++(>= 1.9), RapidJson (at best in some version) and pkgconfig  should be dependencies

```
rpm -qpR pmemkv-devel-1.1-1.fc32.x86_64.rpm
/usr/bin/pkg-config
libpmemkv.so.1()(64bit)
libpmemkv_json_config.so.1()(64bit)
pkgconfig(RapidJSON)
pkgconfig(libpmemkv)
pkgconfig(libpmemobj++) >= 1.9
pkgconfig(memkind) >= 1.8.0
pkgconfig(tbb)
pmemkv(x86-64) = 1.1-1.fc32
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
```

**Comment by lukaszstolarczuk** [comment]
I believe we may set rapidjson as our dependency, but pkg-config seams really not required.
It's easier to handle packages with pkg-config, but we always check for `if(PKG_CONFIG_FOUND)` when we lookup the dependency.

I believe, OS/distros maintainers prefer using pkg-config, that's why they set it up like this.
