### ISSUE TITLE
Use kvtree2 engine by default

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#80]
In docs & standard scripts (and bindings)

Rolls up all changes for:
* https://github.com/pmem/pmemkv/issues/70 (performance)
* https://github.com/pmem/pmemkv/issues/66 (value size reporting)
* https://github.com/pmem/pmemkv/issues/53 (binary safe keys)

**Comment by yuelimv** [comment]
hi @RobDickinson 

Just did a test with the latest repository using kvtree2, it seems still null character is still not supported there? Once key contains a null character, get will return success, but the value will not be there...

**Comment by RobDickinson** [comment]
Thanks for reporting this.  I will set up some additional test cases to see if I can reproduce. Thanks so much for letting me know!
RobD

**Comment by yuelimv** [comment]
Sorry I was not very accurate.. actually when there is a null character in the binary value, Get will return wrong data. Here's the code I used for testing binary keys and values.
[test_bug.cpp.zip](https://github.com/pmem/pmemkv/files/2028178/test_bug.cpp.zip)

**Comment by yuelimv** [comment]
@RobDickinson I submitted a pull request (#97) for this...
