### ISSUE TITLE
Set test timeouts as env var (in build.sh)

### ISSUE THREAD

**Issue by karczex** [pmem/pmemkv#804]
Set test specific timeouts in Cmake 

## Rationale

For long tests (and benchmarks) it's needed to set long timeout. Currently only way to do it is to set global timeout for ctest invocation. This may affect quick tests, and cause bugs escapes, if tests designed to be short, takes long. 

## API Changes

none

## Implementation details

Need to set https://cmake.org/cmake/help/latest/variable/CTEST_TEST_TIMEOUT.html#variable:CTEST_TEST_TIMEOUT for each test

**Comment by igchor** [comment]
I'm not sure if it should be set inside CMake. Test execution time will depend on your platform, whether you run the tests on pmem, etc.

**Comment by karczex** [comment]
So maybe some kind of timeout multiplication per test. Currently you have to pass timeout parameter to ctest to get any reasonable results, which is little bit inconvenient.

**Comment by igchor** [comment]
Hm, I'm not sure if the relative difference in test time will be preserved for different configurations. What's wrong with just having one global timeout? (possibly different for GHA and jenkins?)

**Comment by karczex** [comment]
As we want to implement long tests (hours or even days), global timeout need to be set to virtually infinite value, which could hide some trivial bugs in short tests.

**Comment by igchor** [comment]
So maybe just two separate setting - timeout for short and for long tests? But still, I think it should be set from outside the cmake (through some option or env var?)

**Comment by lukaszstolarczuk** [comment]
as we decided, we'll go with just env_var set for build.sh and run-*.sh scripts.
ref.  #803
