### ISSUE TITLE
Dependance on tbb pkg-config

### ISSUE THREAD

**Issue by loreson** [pmem/pmemkv#817]
# QUESTION: Dependance on tbb pkg-config

## Details

in the CMakeLists.txt there is the line:
list(APPEND PKG_CONFIG_REQUIRES tbb). But tbb does not contain any .pc files.
So I would assume, that this is an error in the CMakeLists.txt. On the other hand that line was added 16 months ago, and I imagine an error would have been caught by now. So what am I missing here?

**Comment by karczex** [comment]
@loreson  Indeed, there is no tbb.pc file in tbb repository, however OS vendors provides this file in packages. 
Are you installing tbb from sources?

Fedora:
```
rpm -qlp tbb-devel-2020.2-1.fc32.x86_64.rpm | grep tbb.pc
/usr/lib64/pkgconfig/tbb.pc
```
Ubuntu: 
```
dpkg --contents libtbb-dev_2020.1-2_amd64.deb  | grep tbb.pc
-rw-r--r-- root/root       272 2020-02-07 01:32 ./usr/lib/x86_64-linux-gnu/pkgconfig/tbb.pc
```

**Comment by lukaszstolarczuk** [comment]
@loreson, did it satisfied your question? If you have more comments please add them here, otherwise we'll close this issue soon.
Thanks for posting your concern.
