### ISSUE TITLE
Error Compiling pmemkv on Ubuntu 18 : undefined reference to ndctl_namespace_get_next_badblock@LIBNDCTL_18

### ISSUE THREAD

**Issue by ch2994** [pmem/pmemkv#839]
# ISSUE: 

## Environment Information

- pmemkv version(s):                                                Current version as of 11/07
- libpmemobj-cpp version(s):                                   Current version as of 11/07
- PMDK (libpmem/libpmemobj) package version(s):                      Current version as of 11/07
- OS(es) version(s):                                                Ubuntu 18
- kernel version(s):                                                 Linux 4.15
- compiler, libraries, packaging and other related tools version(s): 

and possibly:
- TBB version(s):                                                    
- memkind version(s):                                                
- ndctl version(s):                                                  

## Details

Hello, we are trying to compile pmemkv but we keep getting undefined references errors like:

make[4]: Leaving directory '/proj/e6897-PG0/u18-ch/ccssb/pmdk/src/examples/libpmemobj/list_map'
make[4]: Leaving directory '/proj/e6897-PG0/u18-ch/ccssb/pmdk/src/examples/libpmemobj/hashmap'
make[4]: Leaving directory '/proj/e6897-PG0/u18-ch/ccssb/pmdk/src/examples/libpmemobj/tree_map'
../../../debug/libpmemobj.so: undefined reference to `ndctl_namespace_get_next_badblock@LIBNDCTL_18'
../../../debug/libpmemobj.so: undefined reference to `ndctl_namespace_get_first_badblock@LIBNDCTL_18'
../../../debug/libpmemobj.so: undefined reference to `ndctl_dimm_get_dirty_shutdown@LIBNDCTL_18'

The ndctl library we are using is v73 and we built it from source since Ubuntu 18 only has ndctl version 61 (pmemkv requires >=63). We manually built ndctl by following the instruction [here](https://docs.pmem.io/ndctl-user-guide/installing-ndctl/installing-ndctl-from-source-on-linux). 

Can you please help us figure out what needs to be done to get rid of the compilation error? 

Thanks

**Comment by lukaszstolarczuk** [comment]
Hi @ch2994, can you please post the exact command you run, when you got this errors?
And can you please share your command(s) how you built and installed ndctl library?

**Comment by pbalcer** [comment]
Those functions were added in libndctl v63. You seem to have two libndctl versions installed in your system. You need to make sure that the linker that find the appropriate version of libndctl in its search path during the build process. Probably the easiest way to accomplish that would be to remove the ndctl version installed through the OS package manager, and making sure that the ndctl you built from scratch is actually installed in the proper location for your distro.

**Comment by huqianshan** [comment]
Same question with ch29994. But this happens during when i  build pmdk.

after removing ndctl from ubuntu 18.04 distro, i use these commands to build a new pmdk with ndctl > v63
`
$ sudo ./autogen.sh
$ sudo ./configure CFLAGS='-g -O2' --prefix=/usr/local --sysconfdir=/etc --libdir=/usr/local/lib64
$ sudo make
$ sudo make install

$ cd pmdk
$ make 
`

then still having this error

thanks for any advise and comments

**Comment by lukaszstolarczuk** [comment]
I tried to reproduce your issue, using docker image based on [this recipe](https://github.com/pmem/libpmemobj-cpp/pull/978/commits/8257bc70522c8d7cdfca637535747bcb298619b8#diff-3ce3cfbf9d735ca7b8f42b317459760abfc47441bb7a854a9423a1124cbaf5e6).
Using command provided above I got to place, that ndctl was installed in `/usr/local/[lib64]` and got an output like this when checking the installation:
```bash
$ pkg-config --modversion libndctl
Package libndctl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libndctl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libndctl' found
$ PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig pkg-config --modversion libndctl
70.4.gfaa39a6
```
and couldn't event start PMDK's installation:
```bash
$ sudo make
src/common.inc:376: *** Please install libndctl-dev/libndctl-devel >= 63.  Stop.
```

PMDK's `make` worked just fine when I installed ndctl in `/usr` (I used changed configure command):
```bash
$ sudo ./configure CFLAGS='-g -O2' --prefix=/usr --sysconfdir=/etc
```

Perhaps I could easily run PMDK's installation with some env vars (LD_LIBRARY_PATH didn't work with my try), but for sure works if ndctl is installed in system path.

**Comment by lukaszstolarczuk** [comment]
I hope there's no more issues related to this topic, hence I'm closing it. If you need any more assistance, please file a new issue.
