### ISSUE TITLE
Could not add object(s) to the transcation: unknown flags 0x4

### ISSUE THREAD

**Issue by lchx1010** [pmem/pmemkv#850]
# QUESTION: 
There is an error that is "Could not add object(s) to the transcation: unknown flags 0x4" when I run the example which is pmemkv_basic_c in the examples of pmemkv. And other examples have the same error. 
What is the reason for this problem, what should I do next? Thanks.
## Details
Versions :
pmemkv: 1.0
libpmemobj: 1.7
libpmemobj++: 1.8
TBB: 4.4
memkind: 1.10.0

An exception was thrown in line 44 of the following code. The function is pmem::obj::transaction::run in the file that is libpmemobj-cpp-1.8/include/libpmemobj++/transaction.hpp.

```
1. 	template <typename... Locks>
2. 	static void
3. 	run(pool_base &pool, std::function<void()> tx, Locks &... locks)
4. 	{
5. 		int ret = 0;
6. 
7. 		if (pmemobj_tx_stage() == TX_STAGE_NONE) {
8. 			ret = pmemobj_tx_begin(pool.handle(), nullptr,
9. 					       TX_PARAM_CB,
10. 					       transaction::c_callback, nullptr,
11. 					       TX_PARAM_NONE);
12. 		} else {
13. 			ret = pmemobj_tx_begin(pool.handle(), nullptr,
14. 					       TX_PARAM_NONE);
15. 		}
16. 
17. 		if (ret != 0)
18. 			throw pmem::transaction_error(
19. 				"failed to start transaction")
20. 				.with_pmemobj_errormsg();
21. 
22. 		auto err = add_lock(locks...);
23. 
24. 		if (err) {
25. 			pmemobj_tx_abort(err);
26. 			(void)pmemobj_tx_end();
27. 			throw pmem::transaction_error(
28. 				"failed to add a lock to the transaction")
29. 				.with_pmemobj_errormsg();
30. 		}
31. 
32. 		try {
33. 			tx();
34. 		} catch (manual_tx_abort &) {
35. 			(void)pmemobj_tx_end();
36. 			throw;
37. 		} catch (...) {
38. 			/* first exception caught */
39. 			if (pmemobj_tx_stage() == TX_STAGE_WORK)
40. 				pmemobj_tx_abort(ECANCELED);
41. 
42. 			/* waterfall tx_end for outer tx */
43. 			(void)pmemobj_tx_end();
44. 			throw;
45. 		}
46. 
47. 		auto stage = pmemobj_tx_stage();
48. 
49. 		if (stage == TX_STAGE_WORK) {
50. 			pmemobj_tx_commit();
51. 		} else if (stage == TX_STAGE_ONABORT) {
52. 			(void)pmemobj_tx_end();
53. 			throw pmem::transaction_error("transaction aborted");
54. 		} else if (stage == TX_STAGE_NONE) {
55. 			throw pmem::transaction_error(
56. 				"transaction ended prematurely");
57. 		}
58. 
59. 		(void)pmemobj_tx_end();
60. 	}
```

**Comment by igchor** [comment]
It looks like pmemkv uses libpmemobj older than 1.7 (which is the minimal required version). Is is possible that you have some older version installed on your system (e.g. from a package)? If so, can you try setting LD_LIBRARY_PATH env variable to point to the folder with libpmemobj 1.7?

**Comment by lchx1010** [comment]
> 
> 
> It looks like pmemkv uses libpmemobj older than 1.7 (which is the minimal required version). Is is possible that you have some older version installed on your system (e.g. from a package)? If so, can you try setting LD_LIBRARY_PATH env variable to point to the folder with libpmemobj 1.7?

Thank you very much. The problem has been resolved. The reason for this problem is that there are two libpmemobj versions (1.5.1 and 1.7) in the current environment. The older version of libpmemobj was found when running the example, and the example ran successfully after specifying the libpmemobj 1.7 by setting LD_LIBRARY_PATH env variable.
