### ISSUE TITLE
Add vsmap/vcmap engines (volatile hash maps)

### ISSUE THREAD

**Issue by RobDickinson** [pmem/pmemkv#88]
Introduce a new engine that uses persistent memory in volatile mode, skipping all overhead of transactions & flushing for put and remove operations.

**Comment by RobDickinson** [comment]
Met with @vinser52 today and looks like we're on track to have **two** versions of this engine -- a volatile engine that is sorted & single-threaded, and a second volatile engine (based on TBB) that is unordered & thread-safe. This lines up nicely with feature flags (#116) as currently planned. We are waiting for a merge upstream to memkind before we'll be able to include these engines in the pmemkv build. Great progress! :smile: 

ps. There's also an option question of how to include memkind in the build since it doesn't itself have CMake support.  We can treat this like GTest (where the sources are downloaded and built) or request that memkind be improved to work seamlessly with CMake.

**Comment by RobDickinson** [comment]
@vinser52 I updated the available files for the new namespaces (`vmap` and `vcmap`) and related implementation class names (`VMap` and `VCMap`).  I also added these names to the README and ENGINES files (though the ENGINES description still needs to be filled in).

**Comment by RobDickinson** [comment]
@vinser52, this looks great so far.  I updated build/install instructions to include the cpp and memkind repos.  The only gap that I see is we're missing the engine descriptions:  https://github.com/pmem/pmemkv/blob/master/ENGINES.md

**Comment by RobDickinson** [comment]
@vinser52, two build issues as well:

1) Whether or not memkind/cpp/tbb should be optional (whether we need the conditional defines in `pmemkv.cc` as well as additional instructions for what happens when one or more dependencies is missing).  I think I'd prefer to keep things simple and just require all libraries and remove any conditional logic.  (Currently if memkind is not installed the build will break, and I think that's what we want)

2) The C++ examples in `pmemkv-tools` code as well as all high-level bindings currently only link to `pmemkv.so` and are breaking if the vmap or vcmap engines are used.  Guessing this is because memkind & tbb aren't statically linked into `pmemkv.so`?  I realize in saying this that we're probably using the wrong convention today by expecting static linkage with our `.so` file -- the build should be emitting both `pmemkv.so` (dynamically linked) and `pmemkv.a` (statically linked) and all bindings/examples should be referencing `pmemkv.a` (and not `pmemkv.so` like today).  If you could assist with updating the pmemkv core build, I would update all the bindings & examples to match. (or please offer a better suggestion here if you have one)

**Comment by RobDickinson** [comment]
@vinser52, Thanks Sergey for removing the conditional defines for memkind!

I just wanted to give you an update on the second build issue.  Here's an example that works if you use one of the traditional engines, but segfaults if you use the vmap/vcmap engine.

```
g++ baseline.cc -o baseline.bin -O2 -std=c++11 -lpmemkv
PMEM_IS_PMEM_FORCE=1 ./baseline.bin
```

Now of course my first thought was to try something like this:

```
g++ baseline.cc -o baseline.bin -O2 -std=c++11 -lpmemkv -lpmemobj++ -lmemkind
PMEM_IS_PMEM_FORCE=1 ./baseline.bin
```

...but the cpp repo doesn't generate a .so file as far as I can tell.  (Assumes use of cmake)

I also don't know how to pass those extra links against pmemobj++ and memkind up to the high-level bindings.  All the high-level bindings expect a single .so file to bind against at runtime and this isn't something we can change afaik.  So all high-level bindings are basically doing `-lpmemkv` and that's it.

So ideally we'd still just do this and be able to use any engine including those relying on memkind or C++ bindings (or whatever future dependencies we might introduce):

```
g++ baseline.cc -o baseline.bin -O2 -std=c++11 -lpmemkv
PMEM_IS_PMEM_FORCE=1 ./baseline.bin
```

Not only is this easier, but always means those subcomponent versions were tested and packaged together.

I haven't looked at actually changing the build along these lines yet, just thinking through the different issues involved.

**Comment by vinser52** [comment]
@RobDickinson we need to discuss this issues. Because libpmemkv.so has dependensies to libmemkind.so. So, application linked with libpmemkv.so should't care about libmemkind.so. Loader should resolve dependencies automatically.

**Comment by RobDickinson** [comment]
@vinser52, I'm not sure where the problem is -- but the C/C++ examples break if using the "vcmap" or "vmap" engines.  Obviously all the tests in pmemkv core are passing, but the volatile engines always crash when used from pmemkv-tools.  I've tried tinkering with the cmake configuration but haven't made any progress on this.  Help?

**Comment by vinser52** [comment]
@RobDickinson I had reproduced the issue. But after upgrading to the recent version of memkind it went away. Seems it was issue in memkind.

**Comment by RobDickinson** [comment]
@vinser52 I set up a clean Fedora install (following these instructions: https://github.com/pmem/pmemkv/blob/master/INSTALLING.md#fedora) but the C++ example still fails in the same way if I specify the "vcmap" or "vmap" engines.  Note that the example has to be modified because it uses the 'kvtree3' engine by default, and this blows up if you switch it to one of the volatile engine names.  Is it possible I'm missing a configuration step somewhere?  (I'm using the latest versions of memkind and pmdk since this was a totally clean Fedora 27 install)

**Comment by vinser52** [comment]
@RobDickinson Did you change only engine name in the C++ example? Note that for volatile engine we should specify directory path while for persistent engine we are specifying file path. I tried C++ example with vmap engine and also I changed path to "/dev/shm". On my machine everything works fine. Let's discuss it during our upcoming phone call.

**Comment by RobDickinson** [comment]
@vinser52 I can confirm this works as expected when passing a directory name as the path.

Just a few more things to resolve before this can be marked complete:
* This is now blocked by #105 because we previously haven't had any engines that expect a directory name (this was always a file or device)
* Passing in a filename (like the regular examples) should be trapped and reported as an error rather than leading to a crash -- passing in a nonexistent directory fails properly as expected
* Documentation needs to be finished (ENGINES.md)
* Blog post?

**Comment by RobDickinson** [comment]
I was reviewing these test cases and noticed that these had copies of the "recovery" test cases that originated with the persistent collections.  I removed these "recovery" tests as these do not have the same semantic meanings as the persistent versions (and we don't need the duplication).
