### ISSUE TITLE
Fix read-after-flush performance issue in btree engine 

### ISSUE THREAD

**Issue by vinser52** [pmem/pmemkv#90]
read-after-flush memory access pattern impacts performance of write intensive benchmark. Current implementation of btree engine has several places where we could change this pattern to improve performance. In leaf_node_t implementation current_id is updated and flushed on each insert operation. On next access current_id is read. VTune analysis shows that this pattern incurs significant load latency.

**Comment by RobDickinson** [comment]
Hi @vinser52, are there more changes coming for this, or is #104 the complete patch?

**Comment by vinser52** [comment]
This is what I have for nor. But I am going to dig deeper. Hope I will have more performance fixes.
