### ISSUE TITLE
KVEngine::Close() method never called by pmemkv_bench

### ISSUE THREAD

**Issue by vinser52** [pmem/pmemkv#92]
According to the log and code inspection I figured out that Becnhmark class of pmemkv_bench utility never closes properly KVEngine instance. Destructor of KVEngine instance is never called in pmemkv_bench. As a result persistent pool in KVEngine is never closed properly.

**Comment by vinser52** [comment]
The impact of the issue is minor because PMDK should handle the situation when persistent memory pool is not closed due to some reasons.

**Comment by RobDickinson** [comment]
Addressed as part of #93.  Thanks!!!
