### ISSUE TITLE
make pmemkv_config_put_force_create(pmemkv_config *config, bool value) meet customer usage habit

### ISSUE THREAD

**Issue by guoanwu** [pmem/pmemkv#940]
# FEAT: 
make pmemkv_config_put_force_create function to meet customer usage habit

## Rationale
use “cmap” as example. In the API: int pmemkv_config_put_force_create(pmemkv_config *config, bool value); value=1，if no file, will create file, if file exist, the API will fail. Value=0, if no file, fail, if file exist, the data can be recovered. That’s not match the usage habit, really wired, so we would like to have the option that if the file not exist, create file, if file exist, open the file and recover the data. 

## Description

we would like to have the option that if the file not exist, create file, if file exist, open the file and recover the data.  

## API Changes

No need to change the API, just change the API behavior

**Comment by igchor** [comment]
Ref: https://github.com/pmem/pmemkv/issues/576

**Comment by lukaszstolarczuk** [comment]
I'll close this one, since it's covered by #576. The fix will be delivered (most likely) in #944.
