### ISSUE TITLE
BUG: wrong output filenames in CMake

### ISSUE THREAD

**Issue by KFilipek** [pmem/pmemkv#950]
# ISSUE: Wrong output filenames in CMake

## Environment Information

| artifact | version |
| --------- | :--------: |
| pmemkv version(s) | master@a1d8918 |
| libpmemobj-cpp version(s) |master@515f097b |
| PMDK (libpmem/libpmemobj) package version(s) | N/A |
| OS(es) version(s): | Ubuntu 20.10 |
| kernel version(s): | N/A |
| compiler, libraries, packaging and other related tools version(s): | cmake 3.16.3 |

and possibly:
- TBB version(s):                                                    N/A
- memkind version(s):                                                N/A
- ndctl version(s):                                                  N/A

## How often bug is revealed:

(**always**, often, rare) 

## Actual behavior:
```sh
[  0%] Built target checkers
[ 11%] Building CXX object CMakeFiles/pmemkv.dir/src/out.cc.o
[ 22%] Building CXX object CMakeFiles/pmemkv.dir/src/engines-experimental/csmap.cc.o
[ 33%] Building CXX object CMakeFiles/pmemkv.dir/src/libpmemkv.cc.o
[ 44%] Building CXX object CMakeFiles/pmemkv.dir/src/engine.cc.o
[ 55%] Building CXX object CMakeFiles/pmemkv.dir/src/engines/blackhole.cc.o
[ 66%] Building CXX object CMakeFiles/pmemkv.dir/src/iterator.cc.o
[ 77%] Building CXX object CMakeFiles/pmemkv.dir/src/engines/cmap.cc.o
[ 88%] Building CXX object CMakeFiles/pmemkv.dir/src/engines-experimental/stree.cc.o
[100%] Linking CXX shared library libpmemkv.so
```

## Expected behavior:

```sh
[  0%] Built target checkers
[ 11%] Building CXX object CMakeFiles/pmemkv.dir/src/out.o
[ 22%] Building CXX object CMakeFiles/pmemkv.dir/src/engines-experimental/csmap.o
[ 33%] Building CXX object CMakeFiles/pmemkv.dir/src/libpmemkv.o
[ 44%] Building CXX object CMakeFiles/pmemkv.dir/src/engine.o
[ 55%] Building CXX object CMakeFiles/pmemkv.dir/src/engines/blackhole.o
[ 66%] Building CXX object CMakeFiles/pmemkv.dir/src/iterator.o
[ 77%] Building CXX object CMakeFiles/pmemkv.dir/src/engines/cmap.o
[ 88%] Building CXX object CMakeFiles/pmemkv.dir/src/engines-experimental/stree.o
[100%] Linking CXX shared library libpmemkv.so
```

## Additional information about Priority and Help Requested:
| Question | Answer |
| ------------ | ---------- |
| Are you willing to submit a pull request with a proposed change? | Yes |
| Requested priority | Low |

**Comment by igchor** [comment]
@KFilipek why you say the output is wrong? From what I can see I have "*.cc.o" not "*.o" files in CMakeFiles/pmemkv.dir/src/. So it prints the correct filenames

**Comment by KFilipek** [comment]
> @KFilipek why you say the output is wrong? From what I can see I have "_.cc.o" not "_.o" files in CMakeFiles/pmemkv.dir/src/. So it prints the correct filenames

It's not a default behavior. **.cc** should be replaced with **.o**.
From gcc for -c parameter:

> By default, the object file name for a source file is made by
> replacing the suffix .c, .i, .s, etc., with .o

**Comment by lukaszstolarczuk** [comment]
I think it may be expected to use the naming like this. I understand it like that - CMake does not know if you have in the same dir files e.g. `out.c` and `out.cc`, so if you produce `out.o`, not `out.c.o` it may end up wrong. Sooo.. this may be on purpose...

**Comment by igchor** [comment]
Yes, I believe it's intentional and the fact that Cmake does not use default name for binaries is fine imo.
