### ISSUE TITLE
make error: use of deleted function of tbb

### ISSUE THREAD

**Issue by xjqbest** [pmem/pmemkv#954]
## Details

`
mkdir build && cd build && 
cmake .. && 
make
`

do I depend the wrong version of tbb?  thanks!

pmemkv commit id : c2755ccb7c3f21c19605a943b7b3792fbac4d722
tbb commit id : 4523a7615eaed49c4ed75654b349ca41b92c6381
gcc version 7.3.0 (GCC)

![image](https://user-images.githubusercontent.com/12492564/109946424-2eebfb80-7d13-11eb-9c76-009429ddd363.png)

**Comment by lukaszstolarczuk** [comment]
Hi,

I'm afraid the TBB you're using is **too** new. They made some changes recently which change their API, so this may be one of these. See also our issue on our second repo: https://github.com/pmem/libpmemobj-cpp/issues/990

I'm currently using TBB in version 2020.3 (Ubuntu 20.10 + `apt install libtbb-dev`) or installed manually version 2020 (https://github.com/oneapi-src/oneTBB/releases/tag/2020) and it works fine. For now, just please use different version of TBB.

**Comment by xjqbest** [comment]
thanks！ I will try this today

**Comment by xjqbest** [comment]
new error occurs, do I use the wrong version of pmemkv ？ thanks !

![image](https://user-images.githubusercontent.com/12492564/110098984-c0bf3b80-7ddb-11eb-8b63-33d53b458a67.png)

**Comment by igchor** [comment]
@xjqbest what OS are you using? It seems that you use pretty old version of C++ standard library (I see /usr/include/c++/4.8.2). Could you try to update it?

**Comment by xjqbest** [comment]
ok, I will try newer version of gcc, thanks!

**Comment by xjqbest** [comment]
gcc 7.3.0 is ok, thanks !

**Comment by lukaszstolarczuk** [comment]
The first issue mentioned in the thread should be fixed by now (ref. https://github.com/pmem/pmemkv/pull/970), so using current version of TBB (from master) should work.

**Comment by lukaszstolarczuk** [comment]
I hope everything is working fine for you now, I'm closing this issue, but don't hesitate to contact us again if you need our assistance.
