### ISSUE TITLE
Make tx class inherit by transaction

### ISSUE THREAD

**Issue by KFilipek** [pmem/pmemkv#984]
# FEAT: Make tx class inherit by transaction

## Rationale
It good practice to have common interface when it's possible

## Description
Intention of this proposal is to make internals more consistent and readable.

## API Changes
N/A

## Implementation details
Far far away, there is a class tx in src/libpmemkv.hpp:508. It would be nice to inherit by class transaction placed in src/transaction.h. Naturlich, would be nice to rename interface to: "transactional" and then classes will implement it and becomes transactional.

## Meta
N/A

**Comment by igchor** [comment]
But tx from src/libpmemkv.hpp is something different from transaction from src/transaction.h. The first one is just a wrapper around C pointer (pmemkv_tx) and the second one is our internal interface. And so we cannot add inheritance from tx to transaction.

**Comment by KFilipek** [comment]
Okey, I see the consequences of that choice. Inheritance will cause that you can pass every object implementing interface.

**Comment by igchor** [comment]
The problem is that if transaction class would inherit from tx (libpmemkv.cpp) it would also inherit the C pointer member which is useless in the internal implementation.

**Comment by igchor** [comment]
I'll close this issue for now - the db, config and tx from libpmemkv.hpp are abstraction layers built on top of C layer and are not supposed to be used internally. As in pimpl, we have to separate interface from the implementation.
